### ISSUE TITLE
Complete maintainership phase 1 tasks

### ISSUE THREAD

**Issue by jmbowman** [openedx/frontend-platform#414]
Details are here: https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html

If the doc is unclear, please communicate that to Ned Batchelder.  This repository is part of a pilot to determine what qualities an Open edX repository must have to be considered "well maintained".  Similar steps will be needed for the other repositories owned by FED-BOM, but not until we've finalized the requirements after the pilot concludes.

**Comment by jmbowman** [comment]
Please fill out the appropriate entries in https://openedx.atlassian.net/wiki/spaces/COMM/pages/3663233055/Cumulative+Maintainer+Responsibilities also.

**Comment by abdullahwaheed** [comment]
completed suggested tasks, closing it
